title: Info-Coches
description: A minimal and beautiful Jekyll theme best for writing and note-taking.
author: Jesus Cuesta Gomez
avatar: /logo.png
email: jesus.cuestagomez@iesmiguelherrero.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-theme-hamilton

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: Kuushtaa91
  card: summary
logo: logo.png
social:
  name: Jesus Cuesta
  links:
    - https://twitter.com
    - https://www.facebook.com
    - https://github.com
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: es
